import { StyleSheet } from 'react-native';
import { COLORS } from '../../../src/constants/config';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  keyboardAvoid: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, backgroundColor: COLORS.white, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  backButtonText: { fontSize: 24, color: COLORS.text },
  headerTitle: { fontSize: 18, fontWeight: '600', color: COLORS.text },
  headerTitleContainer: { alignItems: 'center' },
  brandName: { fontSize: 11, fontWeight: 'bold', color: COLORS.primary, letterSpacing: 2 },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  mapContainer: { height: 300, margin: 16, borderRadius: 16, overflow: 'hidden' },
  map: { flex: 1 },
  mapPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.surface },
  mapPlaceholderText: { marginTop: 10, color: COLORS.textSecondary, fontSize: 14 },
  driverMarkerStyle: { backgroundColor: COLORS.primary, padding: 8, borderRadius: 20, borderWidth: 2, borderColor: 'white' },
  mapLocationButton: { position: 'absolute', bottom: 16, right: 16, backgroundColor: COLORS.white, paddingVertical: 10, paddingHorizontal: 16, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  locationSection: { backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginBottom: 16 },
  inputRow: { flexDirection: 'row', alignItems: 'center' },
  inputDot: { width: 12, height: 12, borderRadius: 6, marginRight: 12 },
  inputContainer: { flex: 1, position: 'relative' },
  suggestionsContainer: { position: 'absolute', top: '100%', left: 0, right: 0, backgroundColor: COLORS.card, borderRadius: 8, borderWidth: 1, borderColor: COLORS.border, maxHeight: 200, zIndex: 1000, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  suggestionItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  suggestionText: { flex: 1, marginLeft: 8, fontSize: 14, color: COLORS.text },
  inputLabel: { fontSize: 10, color: COLORS.textSecondary, letterSpacing: 1, marginBottom: 4 },
  input: { fontSize: 16, color: COLORS.text, paddingVertical: 8 },
  mapsLinkButton: { flexDirection: 'row', alignItems: 'center', marginTop: 8, paddingVertical: 6, paddingHorizontal: 12, backgroundColor: COLORS.surface, borderRadius: 6, alignSelf: 'flex-start' },
  mapsLinkText: { fontSize: 14, color: COLORS.primary, fontWeight: '500', marginLeft: 4 },
  mapsLinkContainer: { marginTop: 8, backgroundColor: COLORS.surface, borderRadius: 8, padding: 12 },
  mapsLinkInput: { fontSize: 14, color: COLORS.text, paddingVertical: 8, paddingHorizontal: 12, backgroundColor: COLORS.white, borderRadius: 6, borderWidth: 1, borderColor: COLORS.border, minHeight: 60, textAlignVertical: 'top' },
  mapsLinkActions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  mapsLinkCancel: { paddingVertical: 8, paddingHorizontal: 16, backgroundColor: COLORS.surface, borderRadius: 6 },
  mapsLinkCancelText: { fontSize: 14, color: COLORS.textSecondary, fontWeight: '500' },
  mapsLinkSubmit: { paddingVertical: 8, paddingHorizontal: 16, backgroundColor: COLORS.primary, borderRadius: 6 },
  mapsLinkSubmitText: { fontSize: 14, color: COLORS.white, fontWeight: '600' },
  inputConnector: { width: 2, height: 24, backgroundColor: COLORS.border, marginLeft: 5, marginVertical: 4 },
  currentLocationButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 16, paddingTop: 16, borderTopWidth: 1, borderTopColor: COLORS.border },
  currentLocationIcon: { fontSize: 16, marginRight: 8 },
  currentLocationText: { fontSize: 14, color: COLORS.primary, fontWeight: '600' },
  rideTypesSection: { marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: COLORS.text, marginBottom: 12 },
  rideTypeCard: { width: 120, backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginRight: 12, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  rideTypeCardSelected: { borderColor: COLORS.primary, backgroundColor: '#E3F2FD' },
  rideTypeIcon: { fontSize: 32, marginBottom: 8 },
  rideTypeName: { fontSize: 14, fontWeight: '600', color: COLORS.text },
  rideTypeNameSelected: { color: COLORS.primary },
  rideTypeTime: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2 },
  rideTypePrice: { fontSize: 18, fontWeight: 'bold', color: COLORS.text, marginTop: 8 },
  rideTypePriceSelected: { color: COLORS.primary },
  rideTypeDesc: { fontSize: 10, color: COLORS.textSecondary, marginTop: 4, textAlign: 'center' },
  priceEstimate: { backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginBottom: 16 },
  priceBreakdown: { marginBottom: 15 },
  priceBreakdownHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12 },
  priceBreakdownBorder: { height: 1, backgroundColor: COLORS.border, marginVertical: 12 },
  surchargeLabel: { fontSize: 13, fontWeight: '500', color: COLORS.textSecondary, fontStyle: 'italic' },
  surchargeAmount: { fontSize: 13, fontWeight: '600', color: COLORS.textSecondary },
  totalPriceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 12, borderTopWidth: 2, borderTopColor: COLORS.primary, marginTop: 10 },
  totalPriceLabel: { fontSize: 16, fontWeight: 'bold', color: COLORS.text },
  totalPriceValue: { fontSize: 24, fontWeight: 'bold', color: COLORS.primary },
  priceNote: { fontSize: 12, color: COLORS.textSecondary, marginTop: 8, textAlign: 'center' },
  etaContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary, padding: 12, borderRadius: 8, marginBottom: 16, gap: 8 },
  etaText: { color: COLORS.white, fontSize: 16, fontWeight: 'bold' },
  bookButton: { backgroundColor: COLORS.primary, borderRadius: 16, padding: 18, alignItems: 'center', marginBottom: 20 },
  bookButtonDisabled: { opacity: 0.7 },
  bookButtonText: { color: COLORS.white, fontSize: 18, fontWeight: 'bold' },
  statusContainer: { backgroundColor: COLORS.white, borderRadius: 16, padding: 20 },
  statusHeader: { alignItems: 'center', marginBottom: 20 },
  statusTitle: { fontSize: 18, fontWeight: '600', color: COLORS.text, marginTop: 12 },
  driverCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: COLORS.surface, borderRadius: 12, padding: 16, marginBottom: 20 },
  driverInfo: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  driverAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  driverAvatarText: { fontSize: 20, fontWeight: 'bold', color: COLORS.white },
  driverDetails: { flex: 1 },
  driverName: { fontSize: 16, fontWeight: '600', color: COLORS.text },
  driverVehicle: { fontSize: 13, color: COLORS.textSecondary, marginTop: 2 },
  driverPhone: { fontSize: 13, color: COLORS.primary, marginTop: 2, fontWeight: '500' },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  ratingStar: { fontSize: 12, marginRight: 4 },
  ratingText: { fontSize: 12, color: COLORS.text, fontWeight: '600' },
  callButton: { backgroundColor: COLORS.success, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20 },
  callButtonText: { color: COLORS.white, fontWeight: '600' },
  tripDetails: { marginBottom: 20 },
  tripRow: { flexDirection: 'row', alignItems: 'flex-start' },
  tripDot: { width: 12, height: 12, borderRadius: 6, marginTop: 4, marginRight: 12 },
  tripTextContainer: { flex: 1 },
  tripLabel: { fontSize: 10, color: COLORS.textSecondary, letterSpacing: 1, marginBottom: 2 },
  tripText: { fontSize: 14, color: COLORS.text },
  tripConnector: { width: 2, height: 20, backgroundColor: COLORS.border, marginLeft: 5, marginVertical: 4 },
  cancelButton: { backgroundColor: COLORS.error, borderRadius: 12, padding: 14, alignItems: 'center' },
  cancelButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '600' },
  confirmPickupButton: { backgroundColor: COLORS.success, borderRadius: 12, padding: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', marginBottom: 12 },
  confirmPickupButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '700', marginLeft: 8 },
  confirmCompleteButton: { backgroundColor: COLORS.primary, borderRadius: 12, padding: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', marginBottom: 12 },
  confirmCompleteButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '700', marginLeft: 8 },
  packageSection: { backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginBottom: 16 },
  packageTypeContainer: { flexDirection: 'row', gap: 8 },
  packageTypeButton: { flex: 1, paddingVertical: 12, paddingHorizontal: 8, borderRadius: 12, backgroundColor: COLORS.surface, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  packageTypeButtonSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  packageTypeText: { fontSize: 14, fontWeight: '600', color: COLORS.textSecondary },
  packageTypeTextSelected: { color: COLORS.white },
  packageSizeContainer: { flexDirection: 'row', gap: 8 },
  packageSizeButton: { flex: 1, paddingVertical: 12, paddingHorizontal: 8, borderRadius: 12, backgroundColor: COLORS.surface, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6, borderWidth: 2, borderColor: 'transparent' },
  packageSizeButtonSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  packageSizeText: { fontSize: 14, fontWeight: '600', color: COLORS.textSecondary },
  packageSizeTextSelected: { color: COLORS.white },
  sizeHelperText: { fontSize: 11, color: COLORS.textSecondary, marginTop: 8, textAlign: 'center', fontStyle: 'italic' },
  specialInstructionsContainer: { flexDirection: 'row', gap: 8 },
  instructionChip: { flex: 1, paddingVertical: 10, paddingHorizontal: 8, borderRadius: 20, backgroundColor: COLORS.surface, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6, borderWidth: 1, borderColor: COLORS.border },
  instructionChipSelected: { backgroundColor: COLORS.secondary, borderColor: COLORS.secondary },
  instructionChipText: { fontSize: 13, fontWeight: '500', color: COLORS.textSecondary },
  instructionChipTextSelected: { color: COLORS.white },
  packageDetailsInput: { backgroundColor: COLORS.surface, borderRadius: 12, padding: 12, fontSize: 14, color: COLORS.text, minHeight: 60, textAlignVertical: 'top', borderWidth: 1, borderColor: COLORS.border },
  vehicleTypesSection: { marginBottom: 16 },
  vehicleSectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  vehicleTypeContainer: { flexDirection: 'row', gap: 12 },
  vehicleTypeCard: { flex: 1, backgroundColor: COLORS.white, borderRadius: 12, padding: 16, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  vehicleTypeCardSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primary },
  vehicleTypeName: { fontSize: 12, fontWeight: '600', color: COLORS.textSecondary, marginTop: 8 },
  vehicleTypeNameSelected: { color: COLORS.white },
  vehicleTypeDesc: { fontSize: 10, color: COLORS.textSecondary, marginTop: 4, textAlign: 'center' },
  vehicleTypeDescSelected: { color: 'rgba(255,255,255,0.8)' },
  vehicleTypeExamples: { fontSize: 9, color: COLORS.textSecondary, marginTop: 4, textAlign: 'center', fontStyle: 'italic' },
  vehicleTypeExamplesSelected: { color: 'rgba(255,255,255,0.7)' },
  vehicleTypePlaceholder: { fontSize: 13, color: COLORS.textSecondary, fontStyle: 'italic', textAlign: 'center', paddingVertical: 20 },
  interCityToggleContainer: { flexDirection: 'row', backgroundColor: COLORS.surface, borderRadius: 12, padding: 3, marginBottom: 16 },
  interCityToggleButton: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  interCityToggleButtonActive: { backgroundColor: COLORS.primary },
  interCityToggleText: { fontSize: 13, fontWeight: '600', color: COLORS.textSecondary },
  interCityToggleTextActive: { color: COLORS.white },
  interCitySection: { marginBottom: 16 },
  interCityCard: { width: 130, backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginRight: 12, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  interCityCardSelected: { borderColor: COLORS.primary, backgroundColor: '#E3F2FD' },
  interCityCardTitle: { fontSize: 14, fontWeight: '600', color: COLORS.text, marginTop: 8 },
  interCityCardSubtitle: { fontSize: 11, color: COLORS.textSecondary, marginTop: 2 },
  interCityCardPrice: { fontSize: 18, fontWeight: 'bold', color: COLORS.text, marginTop: 8 },
  interCityCardPriceSelected: { color: COLORS.primary },
  surchargeSection: { backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginBottom: 16 },
  surchargeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  surchargeLabel: { flex: 1, fontSize: 14, color: COLORS.text, marginLeft: 8 },
  surchargeValue: { fontSize: 14, fontWeight: '600', color: COLORS.primary },
  bottomNav: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: COLORS.border, paddingVertical: 12, paddingHorizontal: 20 },
  navItem: { flex: 1, alignItems: 'center' },
  navIcon: { fontSize: 24 },
  navText: { fontSize: 12, color: COLORS.textSecondary, marginTop: 4 },
  navTextActive: { color: COLORS.primary, fontWeight: '600' },
});