import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/config';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  keyboardAvoid: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, backgroundColor: COLORS.white, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  backButtonText: { fontSize: 24, color: COLORS.text },
  headerTitle: { fontSize: 18, fontWeight: '600', color: COLORS.text },
  headerTitleContainer: { alignItems: 'center' },
  brandName: { fontSize: 11, fontWeight: 'bold', color: COLORS.primary, letterSpacing: 2 },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },

  stepIndicator: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingHorizontal: 8 },
  stepItem: { flex: 1, alignItems: 'center', position: 'relative' },
  stepCircle: { width: 32, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center', borderWidth: 2 },
  stepCircleActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  stepCircleInactive: { backgroundColor: COLORS.white, borderColor: COLORS.border },
  stepNumber: { fontSize: 14, fontWeight: '700' },
  stepNumberActive: { color: COLORS.white },
  stepLabel: { fontSize: 10, color: COLORS.textSecondary, marginTop: 6, fontWeight: '500' },
  stepLabelActive: { color: COLORS.primary, fontWeight: '600' },
  stepLine: { position: 'absolute', top: 16, left: '60%', width: '80%', height: 2 },
  stepLineActive: { backgroundColor: COLORS.primary },
  stepLineInactive: { backgroundColor: COLORS.border },

  mapCard: { height: 200, borderRadius: 20, overflow: 'hidden', marginBottom: 16, backgroundColor: COLORS.surface },
  mapHeader: { position: 'absolute', top: 12, left: 12, right: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 10 },
  mapHeaderTitle: { fontSize: 13, fontWeight: '700', color: COLORS.text, backgroundColor: COLORS.white + 'E6', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  mapBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: COLORS.white + 'E6', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  mapBadgeText: { fontSize: 11, fontWeight: '600', color: COLORS.success },
  map: { flex: 1 },
  mapPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.surface },
  mapPlaceholderText: { marginTop: 10, color: COLORS.textSecondary, fontSize: 14 },
  driverMarkerStyle: { backgroundColor: COLORS.primary, padding: 6, borderRadius: 14, borderWidth: 2, borderColor: 'white' },

  card: { backgroundColor: COLORS.white, borderRadius: 20, padding: 16, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 8, elevation: 2 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16, gap: 12 },
  iconBox: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  cardTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text },
  cardSubtitle: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2 },

  locationInputs: { gap: 4 },
  inputRow: { flexDirection: 'row', alignItems: 'flex-start' },
  inputDot: { width: 10, height: 10, borderRadius: 5, marginTop: 10, marginRight: 12 },
  inputContainer: { flex: 1, position: 'relative' },
  inputLabel: { fontSize: 10, color: COLORS.textSecondary, letterSpacing: 1, marginBottom: 4, fontWeight: '600' },
  input: { fontSize: 15, color: COLORS.text, paddingVertical: 10, paddingHorizontal: 14, backgroundColor: COLORS.surface, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border },
  suggestionsContainer: { position: 'absolute', top: '100%', left: 0, right: 0, backgroundColor: COLORS.card, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, maxHeight: 200, zIndex: 1000, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  suggestionItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  suggestionText: { flex: 1, marginLeft: 8, fontSize: 14, color: COLORS.text },
  inputConnector: { width: 2, height: 20, backgroundColor: COLORS.border, marginLeft: 4, marginVertical: 2 },
  locationButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 12, paddingVertical: 12, backgroundColor: COLORS.primary + '12', borderRadius: 12, gap: 8 },
  locationButtonText: { fontSize: 14, color: COLORS.primary, fontWeight: '600' },

  toggleRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  toggleButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 14, backgroundColor: COLORS.surface, borderWidth: 2, borderColor: 'transparent' },
  toggleButtonActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  toggleText: { fontSize: 14, fontWeight: '600', color: COLORS.textSecondary },
  toggleTextActive: { color: COLORS.white },

  routeScroll: { marginHorizontal: -4 },
  routeCard: { width: 130, backgroundColor: COLORS.surface, borderRadius: 16, padding: 14, marginHorizontal: 6, alignItems: 'center', borderWidth: 2, borderColor: 'transparent', gap: 6 },
  routeCardSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primary + '10' },
  routeIconBox: { width: 44, height: 44, borderRadius: 22, backgroundColor: COLORS.white, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: COLORS.border },
  routeIconBoxSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  routeName: { fontSize: 13, fontWeight: '700', color: COLORS.text, textAlign: 'center' },
  routeNameSelected: { color: COLORS.primary },
  routeTime: { fontSize: 11, color: COLORS.textSecondary },
  routePrice: { fontSize: 18, fontWeight: '800', color: COLORS.text, marginTop: 4 },
  routePriceSelected: { color: COLORS.primary },

  vehicleBadgeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: COLORS.surface, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: COLORS.border },
  vehicleBadge: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  vehicleBadgeText: { flex: 1 },
  vehicleBadgeName: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  vehicleBadgeDesc: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2 },
  vehiclePriceBadge: { backgroundColor: COLORS.primary + '15', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
  vehiclePriceText: { fontSize: 14, fontWeight: '700', color: COLORS.primary },
  vehiclePlaceholder: { alignItems: 'center', paddingVertical: 24, gap: 8 },
  vehiclePlaceholderText: { fontSize: 13, color: COLORS.textSecondary, fontStyle: 'italic' },

  fieldLabel: { fontSize: 10, color: COLORS.textSecondary, letterSpacing: 1, marginBottom: 6, marginTop: 4, fontWeight: '600' },
  chipRow: { flexDirection: 'row', gap: 8, marginBottom: 4 },
  chip: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12, paddingHorizontal: 10, borderRadius: 12, backgroundColor: COLORS.surface, borderWidth: 2, borderColor: 'transparent' },
  chipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  chipText: { fontSize: 13, fontWeight: '600', color: COLORS.textSecondary },
  chipTextActive: { color: COLORS.white },
  chipOutline: { backgroundColor: COLORS.white, borderColor: COLORS.border },
  chipOutlineActive: { backgroundColor: COLORS.secondary, borderColor: COLORS.secondary },

  sizeRow: { flexDirection: 'row', gap: 10, marginBottom: 4 },
  sizeCard: { flex: 1, alignItems: 'center', paddingVertical: 14, paddingHorizontal: 8, borderRadius: 14, backgroundColor: COLORS.surface, borderWidth: 2, borderColor: 'transparent', gap: 6 },
  sizeCardSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primary + '10' },
  sizeLabel: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  sizeLabelSelected: { color: COLORS.primary },
  sizeDesc: { fontSize: 10, color: COLORS.textSecondary, textAlign: 'center' },
  sizeDescSelected: { color: COLORS.primary },

  textArea: { backgroundColor: COLORS.surface, borderRadius: 14, padding: 14, fontSize: 14, color: COLORS.text, minHeight: 70, textAlignVertical: 'top', borderWidth: 1, borderColor: COLORS.border },

  priceHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  priceHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  priceHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  priceBreakdown: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: COLORS.border },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
  priceLabel: { fontSize: 13, color: COLORS.textSecondary },
  priceValue: { fontSize: 14, fontWeight: '600', color: COLORS.text },
  priceDivider: { height: 1, backgroundColor: COLORS.border, marginVertical: 8 },
  priceTotalLabel: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  priceTotalValue: { fontSize: 18, fontWeight: '800', color: COLORS.primary },
  priceNote: { fontSize: 11, color: COLORS.textSecondary, marginTop: 10, textAlign: 'center', fontStyle: 'italic' },

  bookButton: { backgroundColor: COLORS.primary, borderRadius: 16, padding: 18, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 10, marginTop: 8, shadowColor: COLORS.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  bookButtonDisabled: { opacity: 0.5, shadowOpacity: 0, elevation: 0 },
  bookButtonText: { color: COLORS.white, fontSize: 17, fontWeight: '700' },

  statusContainer: { backgroundColor: COLORS.white, borderRadius: 20, padding: 20 },
  statusHeader: { alignItems: 'center', marginBottom: 20 },
  statusTitle: { fontSize: 18, fontWeight: '600', color: COLORS.text, marginTop: 12 },
  driverCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: COLORS.surface, borderRadius: 14, padding: 16, marginBottom: 20 },
  driverInfo: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  driverAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  driverAvatarText: { fontSize: 20, fontWeight: 'bold', color: COLORS.white },
  driverDetails: { flex: 1 },
  driverName: { fontSize: 16, fontWeight: '600', color: COLORS.text },
  driverVehicle: { fontSize: 13, color: COLORS.textSecondary, marginTop: 2 },
  driverPhone: { fontSize: 13, color: COLORS.primary, marginTop: 2, fontWeight: '500' },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  ratingStar: { fontSize: 12, marginRight: 4 },
  ratingText: { fontSize: 12, color: COLORS.text, fontWeight: '600' },
  callButton: { backgroundColor: COLORS.success, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20 },
  callButtonText: { color: COLORS.white, fontWeight: '600' },
  tripDetails: { marginBottom: 20 },
  tripRow: { flexDirection: 'row', alignItems: 'flex-start' },
  tripDot: { width: 12, height: 12, borderRadius: 6, marginTop: 4, marginRight: 12 },
  tripTextContainer: { flex: 1 },
  tripLabel: { fontSize: 10, color: COLORS.textSecondary, letterSpacing: 1, marginBottom: 2 },
  tripText: { fontSize: 14, color: COLORS.text },
  tripConnector: { width: 2, height: 20, backgroundColor: COLORS.border, marginLeft: 5, marginVertical: 4 },
  cancelButton: { backgroundColor: COLORS.error, borderRadius: 12, padding: 14, alignItems: 'center' },
  cancelButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '600' },
  confirmPickupButton: { backgroundColor: COLORS.success, borderRadius: 12, padding: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', marginBottom: 12 },
  confirmPickupButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '700', marginLeft: 8 },
  confirmCompleteButton: { backgroundColor: COLORS.primary, borderRadius: 12, padding: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', marginBottom: 12 },
  confirmCompleteButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '700', marginLeft: 8 },
  packageSection: { backgroundColor: COLORS.white, borderRadius: 20, padding: 16, marginBottom: 16 },
  packageTypeContainer: { flexDirection: 'row', gap: 8 },
  packageTypeButton: { flex: 1, paddingVertical: 12, paddingHorizontal: 8, borderRadius: 12, backgroundColor: COLORS.surface, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  packageTypeButtonSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  packageTypeText: { fontSize: 14, fontWeight: '600', color: COLORS.textSecondary },
  packageTypeTextSelected: { color: COLORS.white },
  packageSizeContainer: { flexDirection: 'row', gap: 8 },
  packageSizeButton: { flex: 1, paddingVertical: 12, paddingHorizontal: 8, borderRadius: 12, backgroundColor: COLORS.surface, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6, borderWidth: 2, borderColor: 'transparent' },
  packageSizeButtonSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  packageSizeText: { fontSize: 14, fontWeight: '600', color: COLORS.textSecondary },
  packageSizeTextSelected: { color: COLORS.white },
  sizeHelperText: { fontSize: 11, color: COLORS.textSecondary, marginTop: 8, textAlign: 'center', fontStyle: 'italic' },
  specialInstructionsContainer: { flexDirection: 'row', gap: 8 },
  instructionChip: { flex: 1, paddingVertical: 10, paddingHorizontal: 8, borderRadius: 20, backgroundColor: COLORS.surface, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6, borderWidth: 1, borderColor: COLORS.border },
  instructionChipSelected: { backgroundColor: COLORS.secondary, borderColor: COLORS.secondary },
  instructionChipText: { fontSize: 13, fontWeight: '500', color: COLORS.textSecondary },
  instructionChipTextSelected: { color: COLORS.white },
  packageDetailsInput: { backgroundColor: COLORS.surface, borderRadius: 12, padding: 12, fontSize: 14, color: COLORS.text, minHeight: 60, textAlignVertical: 'top', borderWidth: 1, borderColor: COLORS.border },
  vehicleTypesSection: { marginBottom: 16 },
  vehicleSectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  vehicleTypeContainer: { flexDirection: 'row', gap: 12 },
  vehicleTypeCard: { flex: 1, backgroundColor: COLORS.white, borderRadius: 12, padding: 16, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  vehicleTypeCardSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primary },
  vehicleTypeName: { fontSize: 12, fontWeight: '600', color: COLORS.textSecondary, marginTop: 8 },
  vehicleTypeNameSelected: { color: COLORS.white },
  vehicleTypeDesc: { fontSize: 10, color: COLORS.textSecondary, marginTop: 4, textAlign: 'center' },
  vehicleTypeDescSelected: { color: 'rgba(255,255,255,0.8)' },
  vehicleTypeExamples: { fontSize: 9, color: COLORS.textSecondary, marginTop: 4, textAlign: 'center', fontStyle: 'italic' },
  vehicleTypeExamplesSelected: { color: 'rgba(255,255,255,0.7)' },
  vehicleTypePlaceholder: { fontSize: 13, color: COLORS.textSecondary, fontStyle: 'italic', textAlign: 'center', paddingVertical: 20 },
  interCityToggleContainer: { flexDirection: 'row', backgroundColor: COLORS.surface, borderRadius: 12, padding: 3, marginBottom: 16 },
  interCityToggleButton: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  interCityToggleButtonActive: { backgroundColor: COLORS.primary },
  interCityToggleText: { fontSize: 13, fontWeight: '600', color: COLORS.textSecondary },
  interCityToggleTextActive: { color: COLORS.white },
  interCitySection: { marginBottom: 16 },
  interCityCard: { width: 130, backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginRight: 12, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  interCityCardSelected: { borderColor: COLORS.primary, backgroundColor: '#E3F2FD' },
  interCityCardTitle: { fontSize: 14, fontWeight: '600', color: COLORS.text, marginTop: 8 },
  interCityCardSubtitle: { fontSize: 11, color: COLORS.textSecondary, marginTop: 2 },
  interCityCardPrice: { fontSize: 18, fontWeight: 'bold', color: COLORS.text, marginTop: 8 },
  interCityCardPriceSelected: { color: COLORS.primary },
  surchargeSection: { backgroundColor: COLORS.white, borderRadius: 16, padding: 16, marginBottom: 16 },
  surchargeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  surchargeLabel: { flex: 1, fontSize: 14, color: COLORS.text, marginLeft: 8 },
  surchargeValue: { fontSize: 14, fontWeight: '600', color: COLORS.primary },
  bottomNav: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: COLORS.border, paddingVertical: 12, paddingHorizontal: 20 },
  navItem: { flex: 1, alignItems: 'center' },
  navIcon: { fontSize: 24 },
  navText: { fontSize: 12, color: COLORS.textSecondary, marginTop: 4 },
  navTextActive: { color: COLORS.primary, fontWeight: '600' },
});
